INSERT INTO [dbo].[Recorded_Info] ([TEMPERATURE], [HUMANITY], [RAIN], [MOISTURE]) VALUES (1, NULL, NULL, NULL)
INSERT INTO [dbo].[Recorded_Info] ([TEMPERATURE], [HUMANITY], [RAIN], [MOISTURE]) VALUES (1, NULL, NULL, NULL)
